### PR TITLE
Fixes #10 - expiry from entry creation time instead of last access time

### LINKED ISSUE #10: Thredds S3 Caching should use entry creation time instead of last access time for expiry
Thredds S3 caching is currently set to expire cache entries using the last access time of the entry.  This can result in updates to s3 not being reflected in thredds within a predictable time frame.  Would be better to expire cache entries based on creation time to ensure entries don't become stale.

### PR DESCRIPTION
**Pull request by jonescc**

### CODE REVIEW

**Comment by julian1** [comment]
Should this be configurable rather than hard-coded?

Are we sure we don't want to drive the listing from the database? That would avoid the case of having the database being out of sync with what's on S3. Due to eventual consistency issues, as well as non atomic updates?

**Comment by jonescc** [comment]
well it could be configurable - but perhaps that should be tackled via the backlog.

**Comment by julian1** [comment]
If it was driven from the database, then it would also be possible to use an incrementing version integer to ensure cache coherency.

For example, before serving the cached instance it would be possible to do a db lookup to ensure that the version number matches the cached instance - otherwise the file should be invalidated before serving.

**Comment by jonescc** [comment]
Yes that would work better - we'd need to pull this out from the core thredds code - which probably makes sense anyway, and its pretty easy - just needs to be included in a jar - this all pretty dodgy - surprised they put it in in the first place.

**Pull request merged**
